name: Compile fastboot by omnirom 6.0.1
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      USE_CCACHE: "1"
      CCACHE_EXEC: "/usr/bin/ccache"
    steps:
      - name: Configure
        run: |
          curl https://storage.googleapis.com/git-repo-downloads/repo | sudo tee /usr/bin/repo > /dev/null
          sudo ln -sf /usr/bin/python3 /usr/bin/python
          sudo chmod +x /usr/bin/repo
          export DEBIAN_FRONTEND=noninteractive
          sudo apt install -yq bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev libwxgtk3.0-dev python3 openjdk-8-jdk
          git config --global user.email "116288337+freedomSymbol@users.noreply.github.com"
          git config --global user.name "freedomSymbol@bot"
      - name: Get source
        run: |
          mkdir $GITHUB_WORKSPACE/omni
          cd $GITHUB_WORKSPACE/omni
          repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-6.0
          repo sync -c -f --no-tags --no-clone-bundle -j$(nproc --all)
          git clone https://github.com/yonglongliu/system.git new_system
          rm -r system/core
          cp -r new_system/core system/core
          rm -r new_system
          rm -r bootable/recovery
          git clone https://android.googlesource.com/platform/development --single-branch -b android-6.0.1_r74 --no-tags --depth 1
          git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/host/x86_64-w64-mingw32-4.8 --single-branch -b android-6.0.1_r74 --no-tags --depth 1 prebuilts/gcc/linux-x86/host/x86_64-w64-mingw32-4.8
          git clone https://android.googlesource.com/platform/sdk --single-branch -b android-6.0.1_r74 --no-tags --depth 1
          git clone https://android.googlesource.com/platform/external/gtest --single-branch -b android-6.0.1_r74 --no-tags --depth 1 external/gtest
          git clone https://android.googlesource.com/platform/prebuilts/tools --single-branch -b android-6.0.1_r74 --no-tags --depth 1 prebuilts/tools
          git clone https://android.googlesource.com/platform/external/expat --single-branch -b android-6.0.1_r74 --no-tags --depth 1 external/expat
          git clone https://android.googlesource.com/platform/external/fdlibm --single-branch -b android-6.0.1_r74 --no-tags --depth 1 external/fdlibm
      - name: Build
        run: |
          sudo rm -f /usr/bin/python
          sudo apt install -yq python-minimal
          sudo ln -sf /usr/bin/python2 /usr/bin/python
          cd $GITHUB_WORKSPACE/omni
          source build/envsetup.sh
          make -j$(nproc --all) fastboot
          make USE_MINGW=1 -j$(nproc --all) fastboot
      - uses: actions/upload-artifact@v3
        with:
          name: Out host
          path: 'omni/out/host'
